//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MikeUpjohnWebPortfolioV2CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectDateDescription { get; set; }
        public System.DateTime ProjectPostDate { get; set; }
        public string ProjectSummary { get; set; }
        public string ProjectDescription { get; set; }
        public string ProjectLink { get; set; }
        public Nullable<int> ProjectImageID { get; set; }
        public Nullable<int> ProjectThumbnailImageID { get; set; }
        public bool IsDisabled { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime ProjectCreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Image Image { get; set; }
        public virtual Image Image1 { get; set; }
    }
}
